--03/06/2025
--@PLima
--HSF - RESULTADOS EXAMES COM INTERVALO DE 5 MINUTOS
SELECT
    AP.NR_ATENDIMENTO AS NR_ATENDIMENTO,
    PM.NR_PRESCRICAO AS NR_PRESCRICAO,
    SUBSTR(obter_nome_pf(AP.CD_PESSOA_FISICA), 1, 1) || 
    SUBSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), 
    INSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), ' ')) NM_PACIENTE,
    EL.NM_EXAME AS NM_EXAME,
    ELABI.QT_RESULTADO  AS RESULTADO,
    TO_CHAR(ELABI.DT_COLETA,'dd/mm/yyyy hh24:mi') AS DT_COLETA,
    TO_CHAR(ELABI.DT_DIGITACAO,'dd/mm/yyyy hh24:mi') AS DT_DIGITACAO,
    TO_CHAR(ELABI.DT_APROVACAO,'dd/mm/yyyy hh24:mi') AS DT_APROVACAO,
    TO_CHAR(ELABI.DT_IMPRESSAO,'dd/mm/yyyy hh24:mi') AS DT_IMPRESSAO
FROM ATENDIMENTO_PACIENTE AP
INNER JOIN PRESCR_MEDICA PM ON PM.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
INNER JOIN PRESCR_PROCEDIMENTO PP ON PP.NR_PRESCRICAO = PM.NR_PRESCRICAO
INNER JOIN EXAME_LAB_RESULTADO ELR ON ELR.NR_ATENDIMENTO = PM.NR_ATENDIMENTO AND ELR.NR_PRESCRICAO = PP.NR_PRESCRICAO
INNER JOIN EXAME_LAB_RESULT_ITEM ELABI ON ELABI.NR_SEQ_RESULTADO = ELR.NR_SEQ_RESULTADO AND ELABI.NR_SEQ_EXAME = PP.NR_SEQ_EXAME
INNER JOIN EXAME_LABORATORIO EL ON EL.NR_SEQ_EXAME = ELABI.NR_SEQ_EXAME
INNER JOIN EXAME_LAB_PADRAO ELABP ON ELABP.NR_SEQ_EXAME = ELABI.NR_SEQ_EXAME

WHERE PP.NR_SEQ_EXAME IS NOT NULL
AND ELABI.DT_COLETA IS NOT NULL
AND ELABI.DT_APROVACAO IS NOT NULL
AND ELABI.DT_DIGITACAO >= SYSDATE - INTERVAL '5' MINUTE -- Pega exames digitados nos últimos 5 mi
AND (
    CASE
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Ácido%Úrico%') AND ELABI.QT_RESULTADO > 13 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Amilase%') AND ELABI.QT_RESULTADO > 200 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Bilirrubina%') AND ELABI.QT_RESULTADO > 15 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Cálcio%iônico%') AND (ELABI.QT_RESULTADO > 6.6 OR ELABI.QT_RESULTADO < 3.1) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Cálcio%total%') AND (ELABI.QT_RESULTADO > 14 OR ELABI.QT_RESULTADO < 6.3) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Cálcio%') AND (ELABI.QT_RESULTADO > 14 OR ELABI.QT_RESULTADO < 6.3) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Cloro%') AND (ELABI.QT_RESULTADO > 125 OR ELABI.QT_RESULTADO < 75) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Creatinina%') AND ELABI.QT_RESULTADO > 8 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Creatinoquinase%') AND ELABI.QT_RESULTADO > 1000 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Creatino%Fosfoquinase%') AND ELABI.QT_RESULTADO > 1000 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%CK%MB%') AND ELABI.QT_RESULTADO > 30 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Dimero%') AND ELABI.QT_RESULTADO > 1000 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Fosforo%') AND (ELABI.QT_RESULTADO < 1 OR ELABI.QT_RESULTADO > 9) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Glicose%') AND (ELABI.QT_RESULTADO < 60 OR ELABI.QT_RESULTADO > 400) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Lactato%') AND ELABI.QT_RESULTADO > 22 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%LDH%') AND ELABI.QT_RESULTADO > 1000 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Lipase%') AND ELABI.QT_RESULTADO > 700 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Mioglobina%') AND ELABI.QT_RESULTADO > 110 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Potássio%') AND (ELABI.QT_RESULTADO < 2.8 OR ELABI.QT_RESULTADO > 6) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Sódio%') AND (ELABI.QT_RESULTADO < 120 OR ELABI.QT_RESULTADO > 160) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Troponina%') AND ELABI.QT_RESULTADO > 0.7 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Contagem%leucócitos%') AND (ELABI.QT_RESULTADO < 2000 OR ELABI.QT_RESULTADO > 5000) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%leucócitos%') AND (ELABI.QT_RESULTADO < 2000 OR ELABI.QT_RESULTADO > 5000) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%leucocitos%') AND (ELABI.QT_RESULTADO < 2000 OR ELABI.QT_RESULTADO > 5000) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Contagem%plaquetas%') AND (ELABI.QT_RESULTADO < 20000 OR ELABI.QT_RESULTADO > 1000000) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%plaquetas%') AND (ELABI.QT_RESULTADO < 20000 OR ELABI.QT_RESULTADO > 1000000) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Fibrinogênio%') AND ELABI.QT_RESULTADO < 600 THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Hematócrito%') AND (ELABI.QT_RESULTADO < 18 OR ELABI.QT_RESULTADO > 60) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Hemoglobina%') AND (ELABI.QT_RESULTADO < 6.6 OR ELABI.QT_RESULTADO > 19.9) THEN 'CRÍTICO'
        WHEN UPPER(EL.NM_EXAME) LIKE UPPER('%Protrombina%') AND ELABI.QT_RESULTADO > 6 THEN 'CRÍTICO'
        
        ELSE 'NEUTRO'
        END 
        =
        'CRÍTICO'
)
GROUP BY
    AP.NR_ATENDIMENTO,PM.NR_PRESCRICAO,SUBSTR(obter_nome_pf(AP.CD_PESSOA_FISICA), 1, 1) || 
    SUBSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), 
    INSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), ' ')),
    EL.NR_SEQ_EXAME,EL.NM_EXAME,ELABI.QT_RESULTADO,ELABI.DT_COLETA,ELABI.DT_DIGITACAO,ELABI.DT_APROVACAO,ELABI.DT_IMPRESSAO
ORDER BY EL.NM_EXAME, OBTER_NOME_PACIENTE(AP.NR_ATENDIMENTO) , ELABI.DT_DIGITACAO , ELABI.DT_IMPRESSAO                            
                    