--10/06/2025
--@PLima
--HSF - RESULTADOS EXAMES HEMOGRAMA COM INTERVALO DE 58 MINUTOS

SELECT 
    RL.NR_PRESCRICAO, 
    RL.NR_SEQUENCIA, 
    --RL.IE_COBRANCA, 
    --RL.IE_ORIGEM_PROCED, 
    --RL.CD_PROCEDIMENTO, 
    RL.DS_RESULTADO,   
    --RL.NM_USUARIO,
    TO_CHAR(RL.DT_COLETA,'hh24:mi')  DT_COLETA
    --L.IE_FORMATO_TEXTO, 
    --RL.DT_RETIFICACAO, 
    --RL.DT_ATUALIZACAO, 
    --RL.NR_SEQ_PRESCRICAO, 
    --RL.NR_SEQ_EXAME, 
    --RL.IE_FINAL
FROM RESULT_LABORATORIO_V RL
WHERE RL.DT_ATUALIZACAO >= SYSDATE - INTERVAL '58' MINUTE
--WHERE RL.DT_ATUALIZACAO >= SYSDATE - INTERVAL '1440' MINUTE
--AND RL.NR_PRESCRICAO = 5999502
--FETCH FIRST 10 ROWS ONLY
